services:
  - type: web
    name: n8n
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: DB_TYPE
        value: postgresdb
      - key: DB_POSTGRESDB_HOST
        value: your-supabase-host.supabase.co
      - key: DB_POSTGRESDB_PORT
        value: 5432
      - key: DB_POSTGRESDB_DATABASE
        value: your_db_name
      - key: DB_POSTGRESDB_USER
        value: your_db_user
      - key: DB_POSTGRESDB_PASSWORD
        value: your_db_password
      - key: GENERIC_TIMEZONE
        value: Asia/Bangkok
      - key: N8N_BASIC_AUTH_ACTIVE
        value: "true"
      - key: N8N_BASIC_AUTH_USER
        value: yourusername
      - key: N8N_BASIC_AUTH_PASSWORD
        value: yourpassword
